# Creating Arrays

- [Download the lecture notes](https://philchodrow.github.io/PIC16A/content/np_plt/numpy_2.ipynb). 

As described in the previous lecture, `numpy` arrays allow us to write highly readable and performant code when working with batches of numbers. In the next couple lectures, we'll go into a bit more detail about how to create, modify, and retrieve information from arrays. 

## Creating Arrays

As we already discussed, the simplest way to create small, custom arrays in `numpy` is by transforming a list into an array. 

In [1]:
import numpy as np

L = [1, 2, 3, 4]
a = np.array(L)
a

array([1, 2, 3, 4])

`numpy` also offers functions for building a number of common arrays. 

In [2]:
n = 3
np.zeros(n)

array([0., 0., 0.])

In [3]:
np.ones(n)

array([1., 1., 1.])

In [7]:
# random numbers between 0 and 1
np.random.rand(3) # `3` to generates three numbers

array([0.12525482, 0.72590744, 0.74050619])

In [8]:
# an array version of range()
np.arange(3)

array([0, 1, 2])

`np.linspace(start, stop, num=50)`

Generates a fixed-size array of evenly spaced values over a specified interval.

When the third argument (the number of samples to generate) is omitted, np.linspace defaults to generating 50 linearly spaced values between the specified start and end values, inclusive of both endpoints.

In [9]:
# 3 evenly-spaced points between 0  and 1, inclusive
np.linspace(0, 1, 3)

array([0. , 0.5, 1. ])

## Multidimensional Arrays

`numpy` arrays have **dimensions** (or **axes**). So far, we've only worked with one-dimensional arrays. A good way to check the dimensions of an array is with the `shape` attribute: 

In [13]:
n = 3

In [16]:
a = np.ones(n)
print(a)
print(a.shape)

[1. 1. 1.]
(3,)


This says that `a` has a single dimension, and has three entries along that dimension. Here's a 2d array: 
```python
np.ones((rows_number, columns_number))
```

In [20]:
A = np.ones((3, 4))
print(A)
print(A.shape)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(3, 4)


Now, `A` has two dimensions, and has three entries along each dimension. For 2-dimensional arrays, `numpy` will helpfully print out the array in format that makes the dimensions clear. 

You can create arrays of arbitrary numbers of dimensions, although it might be confusing to keep track of them after a while...
```python
np.ones((numbers_of_arrays, numbers_of_rows, numbers_of_column))
```

In [22]:
A = np.ones((3, 4, 5))
A

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [23]:
A.shape

(3, 4, 5)

The `reshape` method allows you to alter the dimensions of an array. For example, let's initialize a 1d array and transform it into a 2d array. 

In [24]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
A = a.reshape(3, 5) # number of "rows" and "columns"
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

We can also undo this operation: 

In [26]:
a = A.reshape(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])